version: '3.8'

services:
    postgres:
        image: postgres:14
        container_name: nestjs-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: nestjs_template
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - nestjs-network

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: nestjs-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 80
        ports:
            - '8080:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres
        networks:
            - nestjs-network

volumes:
    postgres_data:
    pgadmin_data:

networks:
    nestjs-network:
        driver: bridge
